export const CATALOG_TYPES = [
  "Stack",
  "Card",
  "Grid",
  "Heading",
  "Text",
  "Metric",
  "Badge",
  "Alert",
  "Separator",
  "Table",
  "RankList",
  "List",
  "Button",
  "Chart",
  "Image",
  "Tabs",
  "Progress",
  "Timeline",
  "Input",
  "Form",
  "Avatar",
  "ListItem",
  "Code",
  "Map",
  "Carousel",
  "Callout",
  "Accordion",
  "Video",
  "Checkbox",
  "Switch",
  "RadioGroup",
  "Select",
  "Rating",
  "Divider",
  "Column",
  "Row",
  "BarChart",
  "LineChart",
  "Icon",
  "IconText",
  "LineItems",
  "FromTo",
  "KeyValue",
] as const;

export type PrimitiveGroup = { id: string; label: string; sections: string[] };

/** Primitive sections grouped by what the LLM reaches for. */
export const PRIMITIVE_GROUPS: PrimitiveGroup[] = [
  { id: "layout", label: "Layout", sections: ["card-grid", "column-row", "divider", "separator-button", "tabs", "accordion"] },
  { id: "text", label: "Text & status", sections: ["heading-text", "badge", "alert", "callout", "list", "code"] },
  { id: "data", label: "Data display", sections: ["metric", "table", "rank-list", "key-value", "line-items", "from-to", "progress", "timeline", "rating"] },
  { id: "charts", label: "Charts", sections: ["bar-chart", "line-chart", "chart"] },
  { id: "inputs", label: "Inputs", sections: ["input-form", "checkbox-switch", "radio-group", "select"] },
  { id: "media", label: "Media & icons", sections: ["icon-icontext", "avatar", "list-item", "image", "video", "map", "carousel", "carousel-cards"] },
];
